version: '3'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./client:/app/client

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./server:/app/server
    command: npm start
